const { getPrompt } = require("./prompt");
exports.getParameterizedReview = async (req, res) => {
  const { parameters } = req.body;

  const prompt = `A review has been generated by a reviewer taking into consideratoin following points ${JSON.stringify(
    parameters
  )}\nGive a summary of the review in 400 words
    .`;
  const response = await getPrompt({ promptText: prompt });
  console.log(response);
  res.status(200).json(response);
};
